Iter5
alexeilarionov/url-shortener pull request #3
Opened 2023-06-13 10:47 UTC by alexeilarionov

2023-06-13 20:23 UTC, valentinsoe commented on cmd/shortener/main.go
> +		store = storage.NewInMemoryStorage()
Супер, что ты сразу заложил базу под то, с каким хранилищем запускать приложение.
Еще немного аккуратней, будет унести эту логику в пакет storage, а здесь делать вызов вида storage.NewStorage(cfg.Storage) и даже покрыть его тестами:)

2023-06-13 20:25 UTC, valentinsoe commented on internal/app/config/config.go
> +	Storage      string
Занудство(можно не исправлять). Storage не совсем точно отражает смысл данного параметра конфигурации. StorageType кажется подошел бы лучше.

2023-06-13 20:28 UTC, valentinsoe commented on internal/app/hashutil/hashutil.go
> +func Encode(data []byte) string {
Многие использовали вместо hash - генерацию random числа.
Задание на подумать. Какие плюсы и минусы у этих подходов?

2023-06-13 20:31 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +	"github.com/alexeilarionov/url-shortener/internal/app/hashutil"
Настрой пожалуйста в IDE goimports.
Принятый порядок импортов - сначала пакеты стандартной библиотеки, потом внешние пакеты, потом пакеты из текущего репозитория.

2023-06-13 20:40 UTC, valentinsoe commented on internal/app/handlers/handlers_test.go
> +	request := httptest.NewRequest(http.MethodPost, "/", strings.NewReader("test.com"))
Можно в Store положить нужное тебе значение через метод Store. Таким образом этот тест не будет зависеть от работы сокращателя ссылок.
Иначе падение этого теста не обязательно означает проблему именно в этой функции.

2023-06-13 20:41 UTC, valentinsoe requested changes
Спасибо, что сдал работу вовремя! Супер, что соблюдаешь конвенции по стилю кода.
Хорошо, что разделил реализацию на несколько пакетов по функциональному назначению.

Хорошее решение - сделать storage интерфейсом и инициализировать им хендлеры.

Есть небольшие замечания, так как времени на эту работу еще много, рекомендую их исправить.

2023-06-15 21:26 UTC, alexeilarionov commented on cmd/shortener/main.go
> +		store = storage.NewInMemoryStorage()
@valentinsoe перенес. Про тесты, что можно протестировать, логику выбора хранилища исходя из заданных параметров?

2023-06-15 21:33 UTC, alexeilarionov commented on internal/app/hashutil/hashutil.go
> +func Encode(data []byte) string {
мой вариант по идее идемпотентный, для одной и той же строки выдает один и тот-же результат, с генерацией рандомного числа не так. Возможно мой вариант медленнее из-за нескольких операций

2023-06-15 21:44 UTC, alexeilarionov commented
@valentinsoe у меня еще вопрос по вот этой конструкции defer res.Body.Close() статический анализ ругается, что не обрабатывается ошибка, как обычно оформляют закрытие body?

2023-06-15 22:31 UTC, alexeilarionov commented
@valentinsoe  вот такие настройки для оптимизации импортов норм?
<img width="717" alt="CleanShot 2023-06-15 at 23 30 30@2x" src="https://github.com/alexeilarionov/url-shortener/assets/135425425/a8a00785-3abe-4646-8f53-e1a625d075d7">

2023-06-16 08:25 UTC, valentinsoe commented on internal/app/hashutil/hashutil.go
> +func Encode(data []byte) string {
Спасибо за ответ. Ты прав!
Идемпотентность это плюс. Рандом чуть быстрее хэша, но в реальном мире - разницу заметить не удастся.
С рандомом чуть проще решать вопросы колизий(просто сгенерить еще раз).

2023-06-16 08:36 UTC, valentinsoe commented on cmd/shortener/main.go
> +		store = storage.NewInMemoryStorage()
Ну в целом да. Я не говорю, что эти тесты надо сейчас писать. Но такой подход делает принципиально возможным их написание.

2023-06-16 08:50 UTC, valentinsoe approved these changes
Спасибо за исправления и ответы/вопросы.
PR я принимаю. Предлагаю если остались вопросы не специфичные для твоего кода, а отностиельно общие - задавать их в пачке.
Вопрос про статический анализ и defer, давай я напишу пост в пачке. Весьма вероятно что ты не единственный, кто на это наткнулся.

2023-06-16 08:53 UTC, merged