Iter9
alexeilarionov/url-shortener pull request #7
Opened 2023-07-05 15:49 UTC by alexeilarionov

2023-07-07 16:21 UTC, valentinsoe requested changes
Спасибо за работу.
Все классно. Из критичных замечаний - только работа с заголовками для сжатия/разжатия тел запросов и ответов. Остальное не принципиально.

2023-07-07 16:21 UTC, valentinsoe commented on cmd/shortener/main.go
> +	r.Use(logger.RequestLogger)
Хорошее решение, сделать раздельные middleware на каждое действие.
Это позволит их применять "частично" и также сделает их код значительно более простым и читаемым.

2023-07-07 16:21 UTC, valentinsoe commented on internal/app/config/config.go
> +	if envFileStoragePath := os.Getenv("FILE_STORAGE_PATH"); envFileStoragePath != "" {
Если писать такую проверку, то кажется не получится сделать так, чтобы запустить сервер без пути к файлу:)

2023-07-07 16:21 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +	//err = h.Store.Store(encoded, string(body))
Предлагаю комментарий удалить

2023-07-07 16:21 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +func GzipHandler(next http.Handler) http.Handler {
Было бы удобнее читать, если унести такой код в отдельный файл.
Не смешивать код middleware с кодом "бизнесовым"

2023-07-07 16:21 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		contentType := r.Header.Get("Content-Type")
Мы должны сжимать результат в зависимости от типа контента ответа сервера, а не клиента.

2023-07-07 16:21 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		if !strings.Contains(contentType, "application/json") && !strings.Contains(contentType, "text/html") {
Тут должна быть проверка на полное соответствие contentType == "application/json", а не на содержание.
Если в бужущем появиться mime-type "application/json_new", то не факт, что его стоит сжимать.

2023-07-07 16:21 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		if strings.Contains(r.Header.Get("Content-Encoding"), "gzip") {
Тоже неправильно проверять по Contains. Тут должно быть полное совпадение, контент одновременно не может быть сжат разными алгоритмами:)

2023-07-07 16:21 UTC, valentinsoe commented on cmd/shortener/main.go
> +		err := store.(*storage.FileStorage).Save()
Занудство. При таком подходе может быть несколько проблем.
1) приложение упало - мы ничего не сохраним
2) Мы по завершению работы приложения, пытаемся записать, а не можем(нет файла по такому пути и т.д.)

Возможно стоит сохранять данные в файл(дописывать при каждом новом сокращении ссылки), но в таком случае требуется корректно работать с многопоточностью, чего мы пока не проходили.

2023-07-13 20:08 UTC, alexeilarionov commented on cmd/shortener/main.go
> +	r.Use(logger.RequestLogger)
Вынес middleware в отдельный файлик, не совсем понимаю что значит раздельные

2023-07-13 20:25 UTC, alexeilarionov commented on cmd/shortener/main.go
> +		err := store.(*storage.FileStorage).Save()
Пока ничего не делаю тогда по этому замечанию?

2023-07-13 20:26 UTC, alexeilarionov commented on internal/app/handlers/handlers.go
> +func GzipHandler(next http.Handler) http.Handler {
хендлеры и мидлвари? я оставил в одном пакете, но в разных файлах, так норм?

2023-07-14 00:10 UTC, alexeilarionov commented on internal/app/handlers/handlers.go
> +		contentType := r.Header.Get("Content-Type")
если честно, то своими силами так и не смог решить этот вопрос, только с помощью chatgpt получилось

2023-07-14 06:41 UTC, valentinsoe commented on cmd/shortener/main.go
> +	r.Use(logger.RequestLogger)
Раздельные в смысле отдельно middleware которая делает ungzip и отдельно которая делает gzip.
В большинстве работ они склеены в одну.

2023-07-14 06:42 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +func GzipHandler(next http.Handler) http.Handler {
В разных пакетах норм, но в идеале это разные пакеты. 
Это позволит например их использовать повторно в других пакетах(если понадобится когда-то)

2023-07-14 06:43 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		contentType := r.Header.Get("Content-Type")
Молодец что воспользовался современными технологияит.
Но можно с такими вопросами приходить в пачку. Ты не единственный с такой проблемой и мы там это обсуждали с другими студентами.

2023-07-14 06:43 UTC, valentinsoe commented on cmd/shortener/main.go
> +		err := store.(*storage.FileStorage).Save()
Да

2023-07-14 06:45 UTC, valentinsoe approved these changes
Спасибо за исправления!
Во всех обсуждениях ответил, прочитай пожалуйста.

2023-07-14 07:33 UTC, merged